services:
  hasspad:
    container_name: hasspad
    image: kvchen/hasspad:latest
    restart: always
    network_mode: host
    privileged: true
    volumes:
      - type: bind
        source: ./config.yml
        target: /config.yml
        read_only: true
    devices:
      - "/dev/ttyAMA0:/dev/ttyAMA0"
      - "/dev/gpiomem"
